### ISSUE TITLE
No bitches

### ISSUE THREAD

**Issue by JurreSerrarens** [JuliusDeBoer/Tello#1]
I have detected a lack of maidens.
pls fix.

**Comment by BasGarretsen** [comment]
Females are scary, no.

**Comment by JuliusDeBoer** [comment]
![image](https://github.com/JuliusDeBoer/Tello/assets/45075461/bafad28c-50cf-4ed3-892a-a280d401a433)

**Comment by JuliusDeBoer** [comment]
We will not be following up on this issue as it is cringe

**Comment by BasGarretsen** [comment]
Woman are cringe

**Comment by JurreSerrarens** [comment]
![NoBitches](https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fus-tuna-sounds-images.voicemod.net%2Fa08c6a34-e456-40b3-830d-cb02f799ca31-1650737135225.jpg&f=1&nofb=1&ipt=65f4b3716f208e780efe0912c19c0ebe916d40ffc59df34fe37b8632e81d4a99&ipo=images)
