### ISSUE TITLE
Lack of braincells

### ISSUE THREAD

**Issue by BasGarretsen** [JuliusDeBoer/Tello#2]
We're all fucking retarded

**Comment by JuliusDeBoer** [comment]
Yes. And is this relevant in any way?

**Comment by BasGarretsen** [comment]
It is, let me explain why.
在中土世界，有一个强大的魔戒，由黑暗魔君索伦所铸造。这个魔戒有控制所有其他魔戒的力量，但在一次战争中，索伦被击败，魔戒被人类伊西尔杜捡到。然而，伊西尔杜被魔戒腐蚀，在战斗中被杀，魔戒掉入大河，消失了数千年。

几千年后，魔戒被霍比特人比尔博·巴金斯发现。比尔博将魔戒传给他的侄子弗罗多。随着索伦的力量逐渐恢复，他开始寻找魔戒以重新掌控中土世界。巫师甘道夫得知了魔戒的真相，告知弗罗多必须摧毁魔戒才能阻止索伦。

弗罗多与他的朋友们——山姆、梅里和皮聘——开始了一段危险的旅程。他们组成了护戒同盟，其中包括人类阿拉贡、精灵勒苟拉斯、矮人金雳和巫师甘道夫。他们的任务是前往末日火山，将魔戒投入火山熔岩中摧毁。

在旅程中，他们经历了许多艰难险阻，包括被黑骑士追捕，穿越险恶的摩瑞亚矿坑，面对白袍巫师萨鲁曼的背叛，以及在洛丝萝林受到精灵女王盖拉德丽尔的帮助。

在旅程的最后阶段，弗罗多和山姆独自前行，面临戒灵和古老生物咕噜的威胁。与此同时，阿拉贡率领的军队在黑门前与索伦的军队展开决战，为弗罗多争取时间。最终，弗罗多在山姆的帮助下抵达末日火山，但他被魔戒的力量所诱惑。咕噜抢夺魔戒时跌入火山，魔戒被摧毁，索伦的统治也随之结束。

阿拉贡成为刚铎的国王，弗罗多和他的朋友们回到夏尔，但弗罗多受伤太深，决定前往精灵之地疗伤。故事在他们离别中结束，象征着旧时代的结束和新时代的开始。

**Comment by JuliusDeBoer** [comment]
根据所有已知法律
航空业，
蜜蜂没有办法
应该能够飞。
它的翅膀太小，拿不到
它肥胖的小身体离开了地面。
当然，蜜蜂无论如何都会飞
因为蜜蜂不在乎
人类认为不可能的事情。
黄色、黑色。 黄色、黑色。
黄色、黑色。 黄色、黑色。
哦，黑色和黄色！
让我们稍微动一下。
巴里！ 早餐准备好了！
即将到来！
稍等一下。
你好？
- 巴里？
- 亚当？
- Oan 你相信这正在发生吗？
- 我不能。 我来接你。
看上去很犀利。
使用楼梯。 你的父亲
为这些付出了很多钱。
对不起。 我很兴奋。
这是毕业生。
我们为你感到非常骄傲，儿子。
一份完美的成绩单，全都是B。
很自豪。
嘛！ 我这里有事。
- 你的绒毛上有绒毛。
- 噢！ 这就是我！
- 向我们挥手！ 我们将坐在第 118,000 排。
- 再见！
巴里，我告诉过你，
别在屋子里飞了！
- 嘿，亚当。
- 嘿，巴里。
- 那是绒毛凝胶吗？
- 一点。 特别的日子，毕业。
从来没想过我能成功。
小学三天，
高中三天。
那些很尴尬。
大学三天。 我很高兴我接受了
一天，搭便车绕着蜂巢转了一圈。
你确实回来了，不一样了。
- 嗨，巴里。
- 阿蒂，留胡子？ 看起来不错。
- 听说过弗兰基吗？
- 是的。
- 你要去参加葬礼吗？
- 不，我不去。
大家都知道，
蜇人，你就会死。
别把它浪费在松鼠身上。
真是个急性子。
我猜他可能有
刚刚让开。
我喜欢这种结合
我们今天的游乐园。
这就是为什么我们不需要假期。
小伙子，有点威风啊……
在这种情况下。
- 好吧，亚当，今天我们是男人。
- 我们是！
- 蜜蜂人。
- 阿门！
哈利路亚！
学生们、教师们、尊敬的蜜蜂们，
欢迎迪恩·巴兹韦尔。
欢迎，新蜂巢奥蒂
即将毕业的班级...
...9:15。
我们的仪式到此结束。
并开始你的职业生涯
在洪内克斯工业！
我们今天会选择工作吗？
我听说这只是方向。
小心！ 开始了。
保持双手和天线
始终在电车内。
- 想知道会是什么样子？
- 有点可怕。
欢迎来到宏内克斯，
Honesco 的一个部门
也是海克斯康集团的一部分。
就是这个！
哇。
哇。
我们知道你，作为一只蜜蜂，
工作了一辈子
达到你所在的地步
可以工作一辈子。
当我们勇敢的花粉时，蜂蜜就开始了
运动员将花蜜带到蜂巢。
我们的绝密配方
自动进行色彩校正，
气味调节和气泡轮廓
融入这舒缓的甜糖浆中
以其独特的
金色的光芒，你知道...
蜂蜜！
- 那个女孩很性感。
- 她是我的表妹！
- 她是？
- 是的，我们都是表兄弟。
- 正确的。 你说得对。
- 在 Honex，我们不断努力
改善各个方面
蜜蜂的存在。
这些蜜蜂正在进行压力测试
一种新的头盔技术。
- 你认为他会做什么？
- 不够。
这是我们的最新进展，
克雷尔曼。
- 那有什么作用？
- 燕麦那一小串蜂蜜
倒完后它会挂起来。
为我们节省数百万美元。
有人在 Krelman 工作吗？
当然。 大多数蜜蜂的工作是
小的。 但蜜蜂知道
每一个小工作，
如果做得好，意义重大。
但要慎重选择
因为你会留在工作岗位
你选择了你的余生。
余生都做同样的工作吗？
我不知道。
有什么不同？
你会很高兴知道蜜蜂
作为一个物种，没有一天休息过
2700万年后。
所以你就要把我们累死吗？
我们一定会尝试的。
哇！ 这让我大吃一惊！
“有什么不同？”
你怎么能这么说呢？
一份工作永远吗？
这是一个必须做出的疯狂选择。
我放心了。 现在我们只有
做出人生中的一个决定。
但是，亚当，他们怎么可能
从来没有告诉过我们这个？
你为什么要质疑什么？
我们是蜜蜂。
我们是最完美的
地球上正常运转的社会。
你有没有想过也许事情
这里工作有点太好了？
像什么？ 举个例子。
我不知道。 但你知道
我在说什么。
请清理大门。
皇家甘露部队正在接近。
等一下。 哦，出来了。
- 嘿，那些是花粉运动员！
- 哇。
我从来没有这么近距离地看过他们。
他们知道那是什么样子
蜂巢外。
是啊，但有些人就回不来了。
- 嘿，运动员！
- 嗨，运动员！
你们干得很棒！
你们是怪物！
你们真是天外来客！ 我喜欢它！ 我喜欢它！
- 我想知道他们在哪里。
- 我不知道。
他们的日子没有计划。
蜂巢外，飞翔谁知道
在哪里，在做什么谁知道。
你不能仅仅决定成为一名花粉
乔克。 你必须为此而被培养。
正确的。
看。 这样花粉就多了
比你我一生中看到的还要多。
这只是一种身份的象征。
蜜蜂利用得太多了。
也许。 除非你戴了
女士们看到你穿着它。
那些女士们？
他们不也是我们的表兄弟吗？
遥远。 遥远。
看看这两个。
- 一对 Hive Harrys。
- 让我们和他们一起玩吧。
一定很危险
成为一名花粉运动员。
是的。 有一次一只熊压住了我
对抗蘑菇！
他用爪子掐住我的喉咙
另一个，他在打我耳光！
- 天啊！
- 我从没想过我会击倒他。
这期间你在做什么？
试图向当局发出警报。
我可以签名。
一点 今天外面有风，
不是吗，同志们？
是的。 有阵风。
我们正在踏上一片向日葵地
明天距这里六英里。
- 六英里，是吗？
- 巴里！
为我们跳水坑，
但也许你还没有准备好。
- 也许我是。
- 你不是！
我们要去 0900 J-Gate。
你觉得怎么样，嗡嗡声男孩？
你蜜蜂够了吗？
我可能是。 这一切都取决于
关于 0900 的含义。
嘿，霍内克斯！
爸爸，你让我很惊讶。
你决定你对什么感兴趣？
- 嗯，有很多选择。
- 但你只能得到一个。
你是否曾经感到无聊
每天做同样的工作？
儿子，让我告诉你搅拌的事。
你抓住那根棍子，然后你就
移动它，然后搅拌它。
你让自己进入节奏。
这是一件美丽的事情。
你知道，爸爸，
我越想，
也许是蜜田
只是不适合我。
你在想什么，
制作气球动物？
这是一份糟糕的工作
对于一个有毒刺的人来说。
珍妮特，你儿子不确定
他想要进入蜂蜜！
- 巴里，你有时真有趣。
- 我并不是想搞笑。
你一点都不好笑！ 你要去
变成蜂蜜。 我们的儿子，搅拌机！
- 你要当搅局者吗？
- 没人听我说话！
等你看到我有的棍子。
我现在可以说什么。
我要去纹个蚂蚁纹身！
让我们打开一些蜂蜜来庆祝吧！
也许我会刺穿我的胸部。
剃掉我的触角。
和一只蚱蜢住在一起。 得到
一颗金牙，叫大家“dawg”！
我很自豪。
- 今天我们开始工作了！
- 今天就是这一天。
奥姆加油！ 所有的好工作
将会消失。
是的，对。
花粉计数，特技蜜蜂，倾倒，
搅拌机、前台、脱毛...
- 这还能用吗？
- 不挂断。 还剩两个！
其中一份是你的！ 恭喜！
走到一边。
- 你得到了什么？
- 挑出残渣。 恒星！
哇！
一群新手？
是的先生！ 我们的第一天！ 我们准备好了！
做出你的选择。
- 你想先走吗？
- 不，你走吧。
天啊。 有什么可用的？
洗手间服务员开门，
不是因为你想的那样。
- 有机会获得克雷尔曼吗？
- 当然，你在。
抱歉，克雷尔曼刚刚关门。
蜡猴永远开放。
克雷尔曼号再次打开。
发生了什么？
一只蜜蜂死了。 形成一个开口。 看？
他死了。 又一个死人了。
死了。 死了。 又有两人死亡。
从脖子以上都死了。
从脖子以下都死了。 这就是生活！
哦，这太难了！
加热、冷却、
特技蜂、倒水器、搅拌器、
哼哼，七号督察，
lint 协调员、stripe 主管、
螨虫牧马人。 巴里，什么
你认为我应该……巴里吗？
巴里！
好的，我们已经有了向日葵地
在第九象限...
你怎么了？
你在哪里？
- 我要出去。
- 出去？ 出哪儿？
- 在那里。
- 不好了！
我必须在走之前
为我的余生工作。
你会死的！ 你疯了！ 你好？
又一个电话打进来。
如果有人感到勇敢，
83 号有一家韩国熟食店
今天他们得到了玫瑰。
大家好。
- 看那个。
- 这不是我们昨天看到的那个孩子吗？
坚持住，孩子，飞行甲板受到限制。
没关系，卢。 我们要带他上去。
真的吗？ 感觉很幸运，是吗？
在这里签名，在这里签名。 只是最初的那个。
- 谢谢。
- 好的。
今天收到降雨警告，
众所周知，
蜜蜂不能在雨中飞翔。
所以要小心。 一如既往，
注意你的扫帚，
曲棍球棒、狗、
鸟类、熊和蝙蝠。
另外，我还收到了几份报告
根汁汽水倒在我们身上。
墨菲因此呆在家里
像蝉一样叽叽喳喳！
- 那是糟糕的。
- 给各位新手一个提醒，
蜜蜂法则第一，
绝对不能和人类说话！
好吧，发射位置！
嗡嗡，嗡嗡，嗡嗡，嗡嗡！ 嗡嗡声，嗡嗡声，
嗡嗡嗡！ 嗡嗡，嗡嗡，嗡嗡，嗡嗡！
黑色和黄色！
你好！
你准备好了吗，热门人物？
是的。 是啊，带上吧。
风，检查一下。
- 天线，检查一下。
- 花蜜包，检查一下。
- 翅膀，检查一下。
- 斯汀格，检查一下。
吓得我的短裤都脱光了，检查一下。
好吧，女士们，
我们把它搬出去吧！
捣碎那些矮牵牛，
你们这些条纹茎吸盘！
你们所有人，把那些花都沥干吧！
哇！ 我出去了！
我不敢相信我已经出去了！
那么蓝。
我感觉如此快速和自由！
盒子风筝！
哇！
花朵！
这是蓝色领袖。
我们有玫瑰视觉效果。
将其调至 30 度左右并保持。
玫瑰！
30度，罗杰。 把它带到身边。
站到一边吧，孩子。
它有点刺激。
那是一位花蜜采集者！
- 近距离观察过授粉吗？
- 不，先生。
我在这里捡一些花粉，撒在上面
在这里。 也许那里有一个破折号，
捏一下那个。
看到了吗？ 这有点神奇。
太棒了。 我们为什么要这么做？
这就是花粉的力量。 更多花粉，更多
为我们提供鲜花、更多花蜜、更多蜂蜜。
噢。
我捡到了很多亮黄色。
应该是雏菊。 我们不需要那些吗？
哎呀那个视觉效果。
等待。 其中一朵花
似乎正在行动。
再说一遍？ 你正在举报
一朵会动的花？
肯定。
就这样上线了！
这是最酷的。 它是什么？
我不知道，但我很喜欢这个颜色。
闻起来好香。
不像花，但我喜欢它。
是的，模糊。
化学-y。
伙计们，太棒了。 有点抢手了。
我可爱的蜜蜂之王！
奥安迪大脑，下车！
问题！
- 伙计们！
- 这可能会很糟糕。
肯定。
很接近。
会受伤。
妈妈' 是个小男孩。
你的位置太不对了，菜鸟！
像导弹一样向你袭来！
帮我！
我不认为这些是花。
- 我们应该告诉他吗？
- 我想他知道。
这是什么？！
赛点！
你可以开始收拾行李了，亲爱的，
因为你马上就要吃它了！
哟瑟！
总的。
车里有蜜蜂！
- 做一点事！
- 我在开车！
- 嗨，蜜蜂。
- 他回来了！
他要蜇我了！
没人动。 如果你不动的话
他不会蜇你的。 冻结！
他眨了眨眼！
喷他吧，奶奶！
你在干什么？！
哇……紧张程度
这里令人难以置信。
我得回家了。
雨中不能飞。
雨中不能飞。
雨中不能飞。
劳动节！ 劳动节！ 蜜蜂往下掉！
肯，你能关闭吗
请问窗户？
肯，你能关闭吗
请问窗户？
哦，看看我的新简历。
我把它做成了一本折叠式小册子。
你看？ 折叠出来。
不好了。 更多的人类。 我不需要这个。
那是什么？
也许这一次。 这次。 这次。
这次！ 这次！ 这...
窗帘！
那是邪恶的。
这是梦幻般的。 它有我所有的特别之处
技能，甚至是我最喜欢的十部电影。
第一名是什么？ 星球大战？
不，我不会这么做……
...之类的东西。
难怪我们不应该和他们说话。
他们疯了。
当我离开工作面试时，他们
目瞪口呆，简直不敢相信我说的话。
太阳来了。 也许这就是一条出路。
我不记得太阳了
上面有一个大75。
我预测全球变暖。
我能感觉到天气越来越热了。
起初我以为只有我这样。
等待！ 停止！ 蜜蜂！
退后。 这些是冬靴。
等待！
别杀他！
你知道我对它们过敏！
这东西可能会杀了我！
为什么他的人生有
价值比你的低？
为什么他的生命不再那么有价值
比我的？ 这是你的说法吗？
我只是说所有的生命都有价值。 你
不知道他能感受到什么。
我的小册子！
就这样吧，小家伙。
我不怕他。
这是过敏的事情。
把它写在你的简历手册上。
我的整张脸都会浮肿。
让它成为你的特殊技能之一。
将某人击倒
也是一项特殊技能。
正确的。 再见，凡妮莎。 谢谢。
- 凡妮莎，下周？ 酸奶之夜？
- 当然，肯。 你知道，无论如何。
- 你可以把角豆片放在那里。
- 再见。
- 应该减少卡路里。
- 再见。
我得说点什么。
她救了我的命。
我得说点什么。
好吧，就这样吧。
不。
我会说什么？
我真的可能会遇到麻烦。
这是蜜蜂法则。
你不应该和人说话。
我不敢相信我正在这样做。
我得。
哦，我做不到。 奥姆加油！
不，是的。 不。
做吧。 我不能。
我应该如何开始呢？
“你喜欢爵士乐？” 不，那不好。
她来了！ 说话吧，你这个傻瓜！
你好！
对不起。
- 你在说话。
- 是的，我知道。
你说啊！
我很抱歉。
不，谢了。 没关系。
我知道我在做梦。
但我不记得睡觉了。
嗯，我确定这个
非常令人不安。
这让我有点意外。
我的意思是，你是一只蜜蜂！
我是。 我不应该
要做这件事，
但他们都想杀了我。
如果不是你的话...
我不得不感谢你。
我就是这样长大的。
这有点奇怪。
- 我正在和一只蜜蜂说话。
- 是的。
我正在和一只蜜蜂说话。
蜜蜂正在跟我说话！
我只想说我很感激。
我现在就离开。
- 等待！ 你是怎么学会这样做的？
- 什么？
说话的事。
我猜你也是这么做的。
“妈妈，爸爸，亲爱的。” 你把它捡起来。
- 这很有趣。
- 是的。
蜜蜂很有趣。 如果我们不笑的话
我们会因为必须处理的事情而哭泣。
反正...
欧安我...
……给你送东西吗？
- 像什么？
我不知道。 我是说...
我不知道。 奥菲？
我不想把你赶出去。
这不是什么麻烦事。 需要两分钟。
- 这只是咖啡。
- 我讨厌强加。
-别开玩笑了！
- 事实上，我想要一个杯子。
嘿，你想要朗姆酒蛋糕吗？
- 我不应该。
- 有一些。
- 不，我不能。
- 哦，加油！
我正在努力减掉几微克。
- 在哪里？
- 这些条纹没有帮助。
你看起来很棒！
不知道你知不知道
任何关于时尚的事情。
你没事儿吧？
不。
他正在出租车里打领带
当他们飞越麦迪逊时
他终于到了那里。
他跑上台阶进入教堂。
婚礼正在进行中。
他说：“西瓜？
我以为你说的是危地马拉。
我为什么要嫁给西瓜？”
这是蜜蜂的笑话吗？
这就是我们所做的事情。
是的，不同。
那么，你要做什么，巴里？
关于工作？ 我不知道。
我想为蜂巢尽自己的一份力量
但我不能按照他们想要的方式去做。
我知道你的感受。
- 你做？
- 当然。
我的父母希望我成为一名律师或
我是一名医生，但我想成为一名花匠。
- 真的吗？
- 我唯一的兴趣是花。
我们的新女王刚刚当选
与同样的竞选口号。
无论如何，如果你看...
我的蜂巢就在那里。 看见？
你在羊草甸！
是的！ 我就在海龟池旁边！
决不！ 我知道那个地区。
我有一次在那里丢了一个脚趾环。
- 为什么女孩子要把戒指戴在脚趾上？
- 为什么不？
- 就像把帽子戴在膝盖上一样。
- 也许我会尝试一下。
- 你还好吗，女士？
- 哦耶。 美好的。
就喝两杯咖啡吧！
不管怎样，这已经很棒了。
谢谢你的咖啡。
是的，这不麻烦 。
抱歉我没能完成它。 如果我这样做了，
我会度过余生。
你是...？
哦，我随身携带一块？
当然！ 在这里，吃一点面包屑。
- 谢谢！
- 是的。
好的。 好吧...
我想我会再见的。
或不。
好的，巴里。
谢谢你
又说了这么多……之前的事。
哦这个？ 那没什么。
好吧，并不是什么都没有，但是……无论如何……
这不可能行得通。
他已经准备好出发了。
我们不妨尝试一下。
好的，戴夫，拉上降落伞。
- 听起来棒极了。
- 这是惊人的！
那是最可怕的，
我一生中最幸福的时刻。
人类！ 我不敢相信
你和人类在一起！
巨大而可怕的人类！
他们是什么样的人？
巨大而疯狂。 他们说话很疯狂。
他们吃疯狂的巨型东西。
他们开车疯了。
- 他们会像电视上那样试图杀死你吗？
- 他们中有一些。 但有些人没有。
- 你怎么回来的？
- 贵宾犬。
你做到了，我很高兴。 你看到了
无论你想看什么。
你有你的“经验”。 现在轮到你
可以选择你的工作并保持正常。
- 出色地...
- 出色地？
嗯，我遇到了一个人。
你做到了吗？ 她是蜜蜂吗？
- 黄蜂？！ 你父母会杀了你！
- 不，不，不，不是黄蜂。
- 蜘蛛？
- 我对蜘蛛不感兴趣。
我知道这是最热门的事情
有八条腿等等。
我看不惯那张脸。
那么她是谁？
她是……人类。
不，不。 这就是蜜蜂法则。
你不会违反蜜蜂法。
- 她的名字叫凡妮莎。
- 好家伙。
她真好。 而且她还是个花店！
不好了！ 你正在和一个人类花店约会！
我们没有约会。
你飞出蜂巢，说话
对于袭击我们家园的人类
配有电动洗衣机和 M-80！
八分之一一根炸药！
她救了我的命！
她理解我。
一切都结束了！
吃这个。
这还没有结束！ 那是什么？
- 他们称之为面包屑。
- 条纹太刺人了！
那不是他们吃的东西。
这就是他们吃的东西掉下来的东西！
- 你知道 Oinnabon 是什么吗？
- 不。
这是面包、肉桂和糖霜。
他们把它加热...
坐下！
...好热！
- 听我说！
我们不是他们！ 我们就是我们。
这里有我们，也有他们！
是的，但谁能否认
那颗向往的心？
没有什么向往。
别再向往了。 听我说！
你必须开始思考蜜蜂，
我的朋友。 会思考的蜜蜂！
- 思考的蜜蜂。
- 思考的蜜蜂。
会思考的蜜蜂！ 会思考的蜜蜂！
会思考的蜜蜂！ 会思考的蜜蜂！
他在那。 他在泳池里。
你知道你的问题是什么吗，巴里？
我得开始思考蜜蜂？
这种情况还要持续多久？
已经三天了！
你为什么不工作？
我有很多人生重大决定
想一下。
什么生活？ 你没有生命！
你没有工作。 你根本就不是一只蜜蜂！
会杀了你吗
做一点蜂蜜？
巴里，出来吧。
你父亲正在跟你说话。
马丁，你愿意和他谈谈吗？
巴里，我在跟你说话！
你来了？
东西都齐全了吗？
可以了，好了！
前进。 我会赶上的。
不要太长。
看这个！
凡妮莎！
- 我们还在这里。
- 我告诉过你不要对他大喊大叫。
他对喊叫没有反应！
- 那为什么要对我大喊大叫？
- 因为你不听！
我不听这个。
抱歉，我得走了。
- 你要去哪里？
- 我要去见一个朋友。
一个女孩？ 这就是你无法决定的原因吗？
再见。
我只希望她是蜜蜂。
他们有盛大的游行
帕萨迪纳 每年都有花吗？
参加玫瑰花大赛，
这是每个花店的梦想！
漂浮在空中，被包围
鲜花盛开，人群欢呼。
一场锦标赛。 做玫瑰花
参加体育赛事？
不，好吧，我有一个。
怎么不到处飞呢？
真累。 你为什么不
到处跑？ 速度更快了。
是的，好的，我明白了，我明白了。
好吧，轮到你了。
蒂沃。 你可以冻结直播电视吗？
太疯狂了！
你没有那个吗？
我们有 Hivo，但它是一种疾病。
这是一种可怕、可怕的疾病。
天啊。
愚蠢的蜜蜂！
你肯定想蜇那些混蛋。
我们尽量不蜇人。
这对我们来说通常是致命的。
所以你一定要注意自己的脾气。
很小心。
你踢墙，散步，
写一封愤怒的信然后把它扔掉。
像任何情绪一样处理它：
愤怒、嫉妒、欲望。
哦，我的天啊！ 你还好吗？
是的。
- 你怎么了？！
- 这是一个错误。
他没有打扰任何人。
离开这里，你这个混蛋！
那是什么？ 一张“Pic 'N' Save”通告？
是的，确实如此。 你怎么知道？
感觉好像有10页左右。
七十五几乎是我们的极限。
你真的做到了
归结为一门科学。
- 我在意大利《Vogue》杂志上失去了一位表弟。
- 我打赌。
名字里有什么
这是大力神赫拉克勒斯吗？
这是怎么到这里的？
欧特蜂，金花，
雷·利奥塔私人选择？
- 他是那个演员吗？
- 我从没听说过他。
- 为什么会在这里？
- 对于人。 我们吃它。
你没有
你自己的食物够吗？
- 嗯，是。
- 你怎么得到它？
- 蜜蜂做到了。
- 我知道是谁做的！
而且很难做到！
有加热、冷却、搅拌。
你需要一个完整的克雷尔曼的东西！
- 它是有机的。
- 这是我们的有机！
这只是亲爱的，巴里。
只是什么？！
蜜蜂不知道这个！
这是偷窃！ 偷窃多多啊！
你们夺走了我们的家园、学校，
医院！ 这就是我们所拥有的一切！
而且还发售？！
我正在追查到底。
我正在追根究底
所有这一切！
嘿，赫克托。
- 你快完成了吗？
- 几乎。
他就是他
